// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Marquee")>]
[<assembly: AssemblyProductAttribute("Marquee")>]
[<assembly: AssemblyDescriptionAttribute("An open source UI Automation library using Selenium")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Marquee"
    let [<Literal>] AssemblyProduct = "Marquee"
    let [<Literal>] AssemblyDescription = "An open source UI Automation library using Selenium"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
